### ISSUE TITLE
Function forEachAttr not defined in non-minified addtocalender.js file

### ISSUE THREAD

**Issue by peterxjang** [jshor/angular-addtocalendar#11]
Not sure how this happened, but it looks like the function forEachAttr is properly defined in the minified file but not the regular file. (Using the minified version works fine in my tests.)

**Comment by jshor** [comment]
@peterxjang - yeah, in an attempt to clean things up a bit I abstracted some functions to separate files. The files aren't loaded by angular but are included in the minified version.

Is there some reason why the angularaddtocalendar.js file should be used instead of the minified version?

**Comment by peterxjang** [comment]
No, that makes sense now. I was helping someone use this in a Rails project, where the best practice is to use the unminified version and let the asset pipeline handle the rest. Closing the issue, thanks!
