### ISSUE TITLE
Deprecated functions

### ISSUE THREAD

**Issue by skstudios** [jshor/angular-addtocalendar#14]
DropdownController is now deprecated. Use UibDropdownController instead. angular.js:12520:18
dropdown-toggle is now deprecated. Use uib-dropdown-toggle instead. angular.js:12520:18
dropdown-menu is now deprecated. Use uib-dropdown-menu instead. angular.js:12520:18
dropdown is now deprecated. Use uib-dropdown instead.

**Comment by jshor** [comment]
thanks for reporting this - fixed in v1.1.6

**Comment by skstudios** [comment]
Thank you for fixing!
