### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by k-giardchase** [jshor/angular-addtocalendar#2]
First off, thanks for putting this together. It's working perfectly for me and has been a big help.

I was wondering if you had any plans to support a timezone parameter. If not, do you have any suggestions as to how to go about adding that in myself? Thanks again!

**Comment by jshor** [comment]
Glad this helped! In terms of adding in the timezone parameter - I didn't originally have any plans to add timezone support but you're of course welcome to contribute.

If you add it in, the best way would be to make the parameter optional and check if it's set in the controller. Then augment the start/end dates from UTC to whatever the timezone is.
