### ISSUE TITLE
npm build doesn't do anything

### ISSUE THREAD

**Issue by thoughtpalette** [jshor/angular-addtocalendar#21]
While making changes in a fork, `npm test` works as expected, `npm build` doesn't seem to run(?)

Probably a user error.

**Comment by bignall** [comment]
Try `npm run build`. `npm build` is used when building from a folder, like `npm build angular-addtocalendar` run from the parent directory.

**Comment by thoughtpalette** [comment]
Ahh, thanks for the help! That's workin'
