### ISSUE TITLE
Yahoo Timestamp differs from all others

### ISSUE THREAD

**Issue by thoughtpalette** [jshor/angular-addtocalendar#22]
Using 

```
start-date="20161026T100000"
end-date="20161026T113000"
```

Should be 11:30, Yahoo shows 11:00

e.g. Google 

<img width="419" alt="screen shot 2016-09-30 at 2 08 38 pm" src="https://cloud.githubusercontent.com/assets/690624/19003651/73fbe5b0-8717-11e6-95e8-fbd9d595ff13.png">

e.g Yahoo

<img width="280" alt="screen shot 2016-09-30 at 2 08 56 pm" src="https://cloud.githubusercontent.com/assets/690624/19003659/79bc4c56-8717-11e6-9eca-1939e47e117f.png">

**Comment by thoughtpalette** [comment]
ahh welp, seems like the `DUR` parameter is being set incorrectly.

The 1.2 lib sets an hour and a half different as `01.500` in the Query param, whereas it should be `0130`. Looks like being set in `/lib/calendars/getYahooCalendarUrl.js`

On a strict timeline right now for an internal project, otherwise I'd open a PR

**Comment by jshor** [comment]
Thanks for reporting - this was fixed in v1.3.0.
