### ISSUE TITLE
timezone attribute ignored

### ISSUE THREAD

**Issue by thoughtpalette** [jshor/angular-addtocalendar#23]
```
          start-date="20161026T100000"
          end-date="20161026T113000"
          timezone="America/Los_Angeles"
```

With Moment and Moment Timezone (http://momentjs.com/timezone/) installed.

**Comment by thoughtpalette** [comment]
Interestingly, it works when specified via the format attributes example `mm/dd/yyyy hh:mm:ss Z`

**Comment by thoughtpalette** [comment]
ICS files also ignore timezone offset.

**Comment by jshor** [comment]
The `timezone` and `format` attributes are deprecated now. If a timezone option is needed, it can be specified via the `start-date` and `end-date` attributes, given that they are valid RFC2822 or ISO format dates.

Documentation for these deprecated attributes is removed as of v1.3.4.
