### ISSUE TITLE
iCalendar missing PRODID field.

### ISSUE THREAD

**Issue by thoughtpalette** [jshor/angular-addtocalendar#24]
`[PRODID] must be specified once` when running generated ICS file against validator (http://severinghaus.org/projects/icv/)

http://www.kanzaki.com/docs/ical/prodid.html

**Comment by thoughtpalette** [comment]
Also missing UID field and DTSTAMP field for Outlook/ICal

**Comment by jshor** [comment]
Fixed in v1.3.0
