### ISSUE TITLE
uib-dropdown attribute required?

### ISSUE THREAD

**Issue by bignall** [jshor/angular-addtocalendar#27]
The docs say the uib-dropdown attribute is not required and I see in the demo that it is not used (although the uib-dropdown attribute is still generated instead of the dropdown attribute attribute it looks like it should be generating), however I tried and tried to get it working without the uib-dropdown attribute but I couldn't get any drop down that way. I finally decided to add the uib-dropdown attribute and magically it started working.

I couldn't track down why it wasn't working (perhaps there's some missing required library?) so I don't have a pull request to offer for this one.

**Comment by jshor** [comment]
I forgot what version of angular-bootstrap this change occurred on, but if I remember correctly, after that version the bootstrap dropdown became part of ui-bootstrap which necessitated the `uib-dropdown` attribute

**Comment by bignall** [comment]
Ahh. Thanks for the explanation. Maybe more info on that in the Readme and deprecating the old way so that `uib-dropdown` becomes the default eventually?

**Comment by jshor** [comment]
Good catch, I've updated the docs
