### ISSUE TITLE
ICS files date/times broken

### ISSUE THREAD

**Issue by anselanza** [jshor/angular-addtocalendar#3]
Adding to Google Calendar seems to work perfectly without any issues, however, ICS files generated have invalid values, even on the demo page. They come out with lines like this:

`DTSTART;VALUE=DATE:0NaNaNaNTaNaNaN
DTEND;VALUE=DATE:0NaNaNaNTaNaNaN`

And even worse, when generate an iCalendar link more than once on the same page, the ICS file contains duplicated data, e.g.:

`
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
CLASS:PUBLIC
DESCRIPTION:Celebrate the independence of the United States with fireworks in one of the greatest cities in the world.
DTSTART;VALUE=DATE:0NaNaNaNTaNaNaN
DTEND;VALUE=DATE:0NaNaNaNTaNaNaN
LOCATION:Battery Park City, New York, NY
SUMMARY;LANGUAGE=en-us:Fourth of July Fireworks
TRANSP:TRANSPARENT
END:VEVENT
BEGIN:VEVENT
CLASS:PUBLIC
DESCRIPTION:Celebrate the independence of the United States with fireworks in one of the greatest cities in the world.
DTSTART;VALUE=DATE:0NaNaNaNTaNaNaN
DTEND;VALUE=DATE:0NaNaNaNTaNaNaN
LOCATION:Battery Park City, New York, NY
SUMMARY;LANGUAGE=en-us:Fourth of July Fireworks
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR
`

**Comment by jshor** [comment]
Thanks for catching this. Both issues are fixed in 0.0.6.
