### ISSUE TITLE
The demo doesnt work ;)

### ISSUE THREAD

**Issue by claudioschneider** [jshor/angular-addtocalendar#36]
-

**Comment by badbod99** [comment]
Confirmed. Button doesn't appear.

**Comment by milfromoz** [comment]
Found this working example using angularjs http://jsfiddle.net/cyril123/2ELLB/271/

**Comment by jshor** [comment]
Fixed in v1.3.0

**Comment by mattgrande** [comment]
(I'm still not seeing the demo, fyi)

**Comment by jshor** [comment]
@mattgrande thanks, noted. Reopening and will work on this shortly.

**Comment by jshor** [comment]
The demo itself works, but gh-pages is not updating for some reason.

**Comment by jshor** [comment]
Fixed in v1.3.4
