### ISSUE TITLE
Remove dependency on UI library

### ISSUE THREAD

**Issue by crownofapollo** [jshor/angular-addtocalendar#40]
It would be nice to allow the users of the module to make use of whatever UI framework they may already be using rather than requiring another library.

**Comment by KingKarrow** [comment]
I second this. I don't want UI Bootstrap, and it's definitely not a requirement for this directive if you have your own simple dropdown styles.

**Comment by jshor** [comment]
Fixed in v1.3.0. There's now an optional custom css bundled with the package as well as a sass file that can be imported into your project's sass. There's also now an optional parameter `use-bootstrap` if you prefer to go the bootstrap route :)

**Comment by crownofapollo** [comment]
Excellent! Thanks!
