### ISSUE TITLE
Breaking change in v1.3.1?

### ISSUE THREAD

**Issue by mattgrande** [jshor/angular-addtocalendar#44]
Hopefully I'm just missing something... I have everything working fine in v1.3.0. If I try to upgrade to 1.3.1 or 1.3.2, the first line of the minified file references `webpackJsonp`, which doesn't seem to exists.

1. Should it exist somewhere in your files?
2. Is webpack now a requirement to use this library?

Like I said, 1.3.0 seems to be working fine so far, so I was kind of surprised that upping the patch version changed anything...

**Comment by rakelblujeans** [comment]
+1

**Comment by mattgrande** [comment]
Woah, I can't believe I missed this before... v1.3.0 contains all of Angular within it. The dist file is almost half a meg...

@jshor, are you still maintaining this project?

**Comment by jshor** [comment]
Fixed in v1.3.3

**Comment by mattgrande** [comment]
Great! I'll try it out next week (hopefully)!
