### ISSUE TITLE
Main js file is missing when installing v 1.3.2 with bower

### ISSUE THREAD

**Issue by tschofen** [jshor/angular-addtocalendar#45]
In my bower.json dependency section I specified:
"angular-addtocalendar": "^1.3.2"

It pulls version 1.3.2 alright, but the angular-addtocalendar/dist directory has no .js file besides vendor.js.

When I download the zip, there's 'addtocalendar.js'.

If I dump that file into the above directory and build my project, the module no longer works.

It starts with webpackJsonp([0],...

**Comment by cristianodpp** [comment]
same problem here, i cant work with this inside bower... any fix to this ?

**Comment by jshor** [comment]
Fixed in v1.3.3
