### ISSUE TITLE
recurring events

### ISSUE THREAD

**Issue by balazsnemeth** [jshor/angular-addtocalendar#46]
At first, thanks for this awesome and well-maintained library!

Do you plan to add rrule (recurrence) support? Theoretically, would it be possible to specify recurrence rule for google/microsoft/yahoo calendar by URL? (I know the Ics Calendar format does support it)

I found Google calendar render URL support recurrence:  Pass a URL-encoded RRULE or RDATE property with value (e.g., a URL-encoded version of RRULE:FREQ=MONTHLY;BYDAY=2SU would repeat monthly on the second Sunday) via the `recur` parameter to set recurring events. Tested and it still works. ([source](https://stackoverflow.com/a/23495015/1545278))

Thanks,
Balazs

**Comment by jshor** [comment]
This is a great idea. I'll aim to implement this in the near future (possibly targeting the next minor release).

**Comment by eugenedw** [comment]
Just sent over a pull request on a first cut at recurrence (ics).

**Comment by jshor** [comment]
Thanks @eugenedw for your contribution!

Recurrence support is now fully implemented in v1.3.5 for the calendar services that support it. You can now use the following angular attributes for recurring events:

| recurrence-frequency | Event frequency; `DAILY`, `WEEKLY`, `MONTHLY`, `YEARLY`                                            | `Enum`              | No        | `DAILY`              |
| recurrence-interval  | Time between recurrences                                                                           | `Integer`           | No        | `2`                  |
| recurrence-count     | Number of times the event should repeat                                                            | `Integer`           | No        | `4`                  |
| recurrence-end       | Date when the last recurrence should occur                                                         | `String` date       | Yes*      | `20190904T210000`    |
| recurrence-weekstart | Day that the week starts on (default: `SU`); `SU` `MO`, `TU`, `WE`, `TH`, `FR`, `SA`               | `Enum`              | No        | `SU`                 |
| recurrence-weekdays  | Comma-separated days of the week that the event occurs on; `SU` `MO`, `TU`, `WE`, `TH`, `FR`, `SA` | `Enum`              | No        | `TU,TH,SA`           |
| recurrence-monthdays | Comma-separated list of monthdays                                                                  | `String` of numbers | No        | `2,4,6,8`            |
