### ISSUE TITLE
Adding Time to Calendar parameters

### ISSUE THREAD

**Issue by wasifale** [jshor/angular-addtocalendar#52]
Thanks for providing such an awesome library!

Do you plan to add "time" parameter? Theoretically, would it be possible to pass the time along side the date to `addtocalendar` so instead of marking the whole day it mark only the specific time,
For example: I want to add an event to calendar on 9 Oct 2017 at 11:00AM, so that it reminds me about that time, not about the full day.

I've typed from a mobile device so please ignore the errors in typing.

Thanks,
Wasif

**Comment by jshor** [comment]
Thanks for your feedback @wasifale -- I don't plan to add a specific param for time, however you can specify the starting time and ending time of your event as part of the `start-date` and `end-date` params. If you want an all-day event, you can omit `end-date`.
