### ISSUE TITLE
Safari downloads when clicked Google Calendar option

### ISSUE THREAD

**Issue by fajviray** [jshor/angular-addtocalendar#54]
I used Safari v10 and also tried the demo same output, when I select the iCalendar option first it downloads the .ics after that I select the Google calendar it doesn't open the link on a new tab rather downloads an html file. Refreshed the page and select Gcalendar first it works fine.

**Comment by cj-rogers** [comment]
I'm also experiencing this.

Whenever you first download the .ics file and then try any of the url options, it will download the html instead of opening a new tab.

**Comment by jshor** [comment]
Fixed in v1.3.5
