### ISSUE TITLE
angular-addtoCalendar not supported in angular 4

### ISSUE THREAD

**Issue by ghizoulo** [jshor/angular-addtocalendar#55]
Hello, i tried to use this library to my app in angular 4
but I don't know to add it to my module file
I tried 
`import {angular-atc} from 'angular-addtocalendar';` 
But it doesn't work,
Please if someone has a response

**Comment by arushi011** [comment]
same with me.

**Comment by Anjat1155** [comment]
Same here, So please reply

**Comment by libyapages** [comment]
Hello Everybody.
Use this package instead: [@trademe/ng-add-to-calendar](https://www.npmjs.com/package/@trademe/ng-add-to-calendar/v/2.0.1) It works nicely for my Angular 6 project.

**Comment by DishantChanchad1495** [comment]
@libyapages  Thanx you so much for help me

**Comment by jshor** [comment]
Unfortunately this component is not supported for newer angular versions. Please use @trademe/ng-add-to-calendar as @libyapages suggested as an alternative
