### ISSUE TITLE
Calendar event is not getting added in Microsoft calendar and wrong end time is displaying in Yahoo calendar

### ISSUE THREAD

**Issue by kirthigamerlin** [jshor/angular-addtocalendar#59]
Getting below issues while integrating addtocalendar.js in angularjs project:
1. Calendar event is not getting added in Microsoft calendar instead it shows only calendar page.
2. Wrong end time is displaying in Yahoo calendar
3. Downloading / opening multiple event files/tabs on requirement basis. Files not getting downloaded in IOS device. If it is downloaded, downloads only one file in devices but in desktop it's working as expected.

I added following files & dependencies but still no luck. Please let me know if I missed out anything:
addtocalendar.js - v1.3.4
moment.min.js
clickoutside.directive.js
fileSaver.js
Blob.js

Kindly help me to solve the issue.
Thanks in advance

**Comment by jshor** [comment]
Thanks for reporting. These issues are all fixed in v1.3.5.
