### ISSUE TITLE
Unknown provider: eProvider 

### ISSUE THREAD

**Issue by teamtaheny1** [jshor/angular-addtocalendar#6]
Hey, thanks for the module, saved me a ton of time.   I had an issue using it when concated and minified in a vendor rollup file becasue of dependency injection.  To make it work had to update controller code like so:

	.controller('AddtocalendarCtrl',['$scope',function($scope) {

and add closing square bracket to line 117.

**Comment by jshor** [comment]
Ah, sorry about that, thanks for reporting. It's fixed in v1.1.2.
